version: '3.8'

services:
  app:
    image: user
    environment:
      - SPRING_APPLICATION_NAME=UserService
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/finances
      - SPRING_DATASOURCE_USERNAME=finance_user
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=10
      - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=5
      - SERVER_PORT=8083
    depends_on:
      - db
    ports:
      - "8083:8083"
    command: ["java", "-jar", "/app/app.jar"]
    volumes:
      - .:/app

  db:
    image: postgres
    environment:
      - POSTGRES_DB=finances
      - POSTGRES_USER=finance_user
      - POSTGRES_PASSWORD=12345
    ports:
      - "5435:5432"
